POST http://localhost:4002/products
content-type: application/json

{
    "name": "red pen",
    "price": 5
}

###
GET http://localhost:4002/products

###
GET http://localhost:4002/products/9d1a9826-60df-420d-b955-b13d40cb8ec1

###
PUT http://localhost:4002/products/3cb0e3cb-1ef5-48a0-a76f-a6945d42e21d
content-type: application/json

{
    "name": "grey plus pen",
    "price": 15
}

###
DELETE http://localhost:4002/products/a88945b6-719e-4ed9-b8d0-9d5ce2845a1e